### ISSUE TITLE
RouteAI - Create a new route causes error

### ISSUE THREAD

**Issue by tsseppa** [Jekblade/Orienteering#2]
Creating a new error causes two errors. First occurs when selecting the end control for the leg, and second when selecting the analysis area. 

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/OrienteeringRoutesApp-NewVersion/RouteAI/LeastCostPath.py", line 367, in finish_polygon
    self.area.append(self.area[0])
                     ~~~~~~~~~^^^
IndexError: list index out of range
```
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/Users/user/Documents/OrienteeringRoutesApp-NewVersion/RouteAI/LeastCostPath.py", line 376, in finish_polygon
    self.complete_selection(self.area)
  File "/Users/user/Documents/OrienteeringRoutesApp-NewVersion/RouteAI/LeastCostPath.py", line 384, in complete_selection
    self.map_type = self.map_type.get()
                    ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

**Comment by Jekblade** [comment]
Fixed the main error (self.map_type.get()) because of wrong notation. The second error however is still a mistery, but for now it doesnt affect the use of the app👍

**Comment by Jekblade** [comment]
Fixed, had to check if an area Has begun selection - only then check for the release of Button1
